Feature/12 publication icon
PiterPy-Meetup/postpost-frontend pull request #17
Opened 2019-02-23 16:47 UTC by TheCollapse

Add template for PublicationItemPlatformIcon.

Closes #12

2019-02-23 21:45 UTC, b0g3r requested changes
Спасибо за вклад! К сожалению, прямо сейчас мы не сможем это смёрджить — сначала нужно будет разобраться с мёрдж-реквестом со сторибуком, а потом перенести изменения отсюда на стабильную версию кода со сторибуком. Впрочем, я оставил комментарии: они касаются типизации и небольших просьб к оформлению кода.

2019-02-23 21:45 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +    const SOCIAL_NETWORKS_MAPPING: object = {
```suggestion
const SOCIAL_NETWORKS_MAPPING: Readonly<Map<string, string>> = new Map([
    ['twitter', require('../assets/social_logos/twitter.svg')],
    ['facebook', require('../assets/social_logos/facebook.svg')],
    ['vk', require('../assets/social_logos/vk.svg')],
    ['instagram', require('../assets/social_logos/instagram.svg')]
    ['telegram', require('../assets/social_logos/telegram.svg')]
])
```

2019-02-23 21:45 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +    const AVAILABLE_SOCIAL_NETWORKS: string[] = ['twitter', 'facebook', 'vk', 'instagram', 'telegram'];
Тогда эта штука не нужна будет

2019-02-23 21:45 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +    const SOCIAL_NETWORKS_MAPPING: object = {
И название можно что-нибудь типа ICONS_BY_SOCIAL_NETWORK

2019-02-23 21:45 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +                return AVAILABLE_SOCIAL_NETWORKS.includes(value);
Можно будет заменить на `SOCIAL_NETWORKS_MAPPING.has(socialType)`

2019-02-23 21:45 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +    Icon with social networks
Я бы доку дополнил, что доступно только пять социалок. Что на вход принимает ссылку на аватарку

2019-02-23 21:45 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +    Icon with social networks
Возможно ещё стоит добавить какую-то картинку заглушку, если соцсети нет

2019-02-23 21:45 UTC, b0g3r commented on src/stories/PublicationItemPlatformIcon.js
> +    .addDecorator(withKnobs)
Посмотрел по проекту — везде по два пробела отступы 🤔 Поправишь?

2019-02-23 21:45 UTC, b0g3r commented on src/stories/PublicationItemPlatformIcon.js
> +                            :image="image" :socialType="socialType"
Здесь и ниже нужно использовать kebab-case для пропсов:
```suggestion
                            :image="image" :social-type="socialType"
```

2019-02-23 21:45 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +        <v-avatar class="socialNetwork" :size="socialIconSize">
Поресёчь, пожалуйста, за нейминг классов для css, мне казалось что lowerCamelCase это не для css

2019-02-23 22:52 UTC, TheCollapse commented on src/components/PublicationItemPlatformIcon.vue
> +    Icon with social networks
Мб лучше вообще ничего не отображать? 🤔

2019-02-24 08:47 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +    Icon with social networks
Ой, я не соцсеть имел в виду, а аватарку

2019-02-25 15:44 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +        top: 27px;
меня ещё смущает здесь абсолютное позиционирование на пикселях

2019-02-25 15:45 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +        top: 27px;
не встрянем с абсолютными размерами иконок?

2019-02-25 15:47 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +        public image!: string;
я бы переименовал в более значащее `avatar`

2019-02-25 16:21 UTC, TheCollapse commented on src/components/PublicationItemPlatformIcon.vue
> +        top: 27px;
![image](https://user-images.githubusercontent.com/6180209/53351467-68264f80-3932-11e9-898a-ba5540511d9a.png)

Не-а. Если только у нас не будут изменяемые размеры аватарок и иконок соц. сетей.

2019-02-25 16:24 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +        top: 27px;
А мне кажется будет

2019-02-25 16:24 UTC, TheCollapse commented on src/components/PublicationItemPlatformIcon.vue
> +        <v-avatar class="socialNetwork" :size="socialIconSize">
![image](https://user-images.githubusercontent.com/6180209/53351898-ebe03c00-3932-11e9-93a4-bff94a5325df.png)

Да, ты прав.

2019-02-25 16:29 UTC, TheCollapse commented on src/components/PublicationItemPlatformIcon.vue
> +        top: 27px;
Какие?

2019-02-25 16:33 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +        top: 27px;
Идеально будет если этот компонент будет заполнять всю выданную ему высоту. Чтобы им можно было управлять обычным css, и он скелился как может

2019-02-25 16:36 UTC, TheCollapse commented on src/components/PublicationItemPlatformIcon.vue
> +        top: 27px;
Ок. я могу сделать, чтобы можно было эти пропсы пробрасывать в компонент, но насколько это нужно? Много ли где он будет использоваться?

2019-02-25 16:38 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +        top: 27px;
Так дело не в пропсах ведь. Я ж говорю — было бы клёво если оно бы управлялось снаружи css, а внутри занимало всю доступную область

2019-02-25 16:38 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +        top: 27px;
Как асбтрактная вьютифай кнопка занимает все что может по ширине

2019-02-25 16:39 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +        top: 27px;
Хочешь ужать - суй ее в грид

2019-02-25 16:41 UTC, TheCollapse commented on src/components/PublicationItemPlatformIcon.vue
> +        top: 27px;
Понял, посмотрю.

2019-02-25 17:55 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +        top: 27px;
можно ещё смотреть в сторону postcss — если будут проблемы с подключением в сторибуках я помогу

2019-02-27 18:37 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +    const SOCIAL_NETWORKS_MAPPING: object = {
Проверил — вебшторм ругается, но по глупости, сам тайпскрипт не ругается

2019-02-27 18:38 UTC, TheCollapse commented on src/components/PublicationItemPlatformIcon.vue
> +    const SOCIAL_NETWORKS_MAPPING: object = {
Ок, посмотрю, спасибо.

2019-02-27 18:38 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +    const SOCIAL_NETWORKS_MAPPING: object = {
Можно либо выключить проверку вебшторма в этом месте, либо добавить `as ReadonlyMap<string, string>`

2019-02-27 18:38 UTC, TheCollapse commented on src/components/PublicationItemPlatformIcon.vue
> +    const SOCIAL_NETWORKS_MAPPING: object = {
2 выглядит как костыль. :с

2019-02-27 18:39 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +    const SOCIAL_NETWORKS_MAPPING: object = {
ну лучше чем выключение проверки, мне кажется

в этом случае ещё нужно будет вынести requir'ы в отдельные константы

2019-02-27 18:48 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +    const SOCIAL_NETWORKS_MAPPING: object = {
Пути жса неисповедимы
```    const TWITTER_AVATAR: Readonly<string> = require('../assets/social_logos/twitter.svg') as string;
    ...
    const SOCIAL_NETWORKS_MAPPING: ReadonlyMap<string, string> = new Map([
      ['twitter', TWITTER_AVATAR],
      ...
    ]) as ReadonlyMap<string, string>;
```

2019-02-27 18:56 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +    const SOCIAL_NETWORKS_MAPPING: object = {
На вопрос зачем так заморачиваться с импортами рассказывает дока:
https://palantir.github.io/tslint/rules/no-var-requires/
tldr: require и import — страшные волшебные слова, которые жутко неопределённые. Поэтому использовать их нужно только в специально отведенных местах, а все импортируемые модули должны быть понятны тайпскрипту (для этого их приходится описывать отдельно)

2019-03-01 11:51 UTC, b0g3r requested changes

2019-03-01 11:51 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +            return ICONS_BY_SOCIAL_NETWORK.get(this.socialType);
.get() может вернуть undefined, я бы добавил какую-нибудь иконку с вопросом и делал бы
`return ICONS_BY_SOCIAL_NETWORK.get(this.socialType) || 'unknownNetwork'`

2019-03-01 11:51 UTC, b0g3r commented on src/stories/PublicationItemPlatformIcon.js
> +              'facebook',
мне интересно, можно ли получать этот список из компонента прям 🤔

2019-03-01 11:51 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +    .inner-icon {
![image](https://user-images.githubusercontent.com/19777948/53636480-707fd280-3c31-11e9-9af8-2a4fa1940f88.png)
потерялась белая обводка

2019-03-01 11:52 UTC, TheCollapse commented on src/components/PublicationItemPlatformIcon.vue
> +            return ICONS_BY_SOCIAL_NETWORK.get(this.socialType);
Принял.

2019-03-01 11:53 UTC, TheCollapse commented on src/stories/PublicationItemPlatformIcon.js
> +              'facebook',
Не думаю, но можно его прокидывать снаружи.

2019-03-01 11:53 UTC, TheCollapse commented on src/components/PublicationItemPlatformIcon.vue
> +    .inner-icon {
Не учел ее, поправлю.

2019-03-01 13:08 UTC, b0g3r commented on src/stories/PublicationItemPlatformIcon.js
> +              'facebook',
А у меня получилось!

У константы нужно добавить `export`, здесь импортировать именованным импортом `import { ICONS_BY_SOCIAL_NETWORK } from '../components/PublicationItemPlatformIcon.vue';` и использовать как `Array.from(ICONS_BY_SOCIAL_NETWORK.keys()),`

2019-03-01 13:17 UTC, TheCollapse commented on src/stories/PublicationItemPlatformIcon.js
> +              'facebook',
Хмм, про экспорт не подумал, спасибо.

2019-03-01 16:34 UTC, b0g3r commented on src/stories/PublicationItemPlatformIcon.js
> +const SOCIAL_NETWORK_ICONS = Array.from(ICONS_BY_SOCIAL_NETWORK.keys()).concat('unknown');
Кажется, здесь лишний concat

2019-03-01 16:34 UTC, b0g3r commented on src/stories/PublicationItemPlatformIcon.js
> +            'twitter')
лучше тогда `SOCIAL_NETWORK_ICONS[0]`

2019-03-01 16:34 UTC, b0g3r commented on src/stories/PublicationItemPlatformIcon.js
> +          networkIcons: SOCIAL_NETWORK_ICONS.slice(),
идея отличная 👍

2019-03-01 16:34 UTC, b0g3r commented on src/components/PublicationItemPlatformIcon.vue
> +        <img class="outer-icon" :src="avatarIcon" @error="onAvatarDownloadError" alt="avatar"/>
Немного другой механизм с пустой аватаркой -- на вход в компонент может прийти null вместо avatar, и это должно нормально отработать.
Также стоит добавить в сторибук и проверить как оно работает

2019-03-02 12:41 UTC, b0g3r approved these changes

2019-03-02 12:45 UTC, merged